// ==== Adding about route
export const metadata = {
  title: "About New project",
  // description: "Generated by Next.js"
}
export default function About() {
    return (
      <>
        <h1>About page!</h1>
      </>
    );
  }
  
